### ISSUE TITLE
[Feature] Auto formating

### ISSUE THREAD

**Issue by vanko0309** [SurenAt93/monaco-react#11]
When the component loads with content it does not auto-format it, could you please explain how to do it or give access to editor.getAction('editor.action.format') methods.

**Comment by SurenAt93** [comment]
You have access to the editor instance. You can find it in "editorDidMount" prop, as a second argument. [More about "editor instance"](https://github.com/SurenAt93/monaco-react#editor-instance)

Also, see the example [here](https://codesandbox.io/s/monaco-editorreact---editor-instance-zgh90).

Let me know if it helps.

**Comment by vanko0309** [comment]
Great, thanks, that works!

**Comment by SurenAt93** [comment]
And one more thing; if you are working with `json`, maybe you can avoid thinks like `editor.getAction('editor.action.format')`. It depends on your case.

**Comment by vanko0309** [comment]
I need to format HTML content, I tried using the above example and to trigger editor.getAction('editor.action.formatDocument').run();, but sadly the content doesn't format. Do you have an idea of how I can handle this case?

**Comment by SurenAt93** [comment]
Could you please create a simple example in codesandbox to reproduce it?

**Comment by vanko0309** [comment]
Sure, this is the same thing that happens to me. 
https://codesandbox.io/s/monaco-editorreact---editor-instance-1wxfm

**Comment by SurenAt93** [comment]
okay, I see...

One way to fix it is - just replace your `handleEditorDidMount` method in the example above with this one:

```js
  handleEditorDidMount(event, editor) {
    const handler = editor.onDidChangeModelDecorations(_ => {
      handler.dispose();
      editor.getAction("editor.action.formatDocument").run();
    });
  }
```

**Comment by vanko0309** [comment]
Exactly what I needed, thanks a lot!!

**Comment by MRzNone** [comment]
Are there auto-formatter available naively for SQL?

Sanbox: https://codesandbox.io/s/monaco-editorreact---editor-instance-vjflc?file=/src/index.js
