### ISSUE TITLE
ControlledEditor doesn't update when value changes in readOnly mode

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [SurenAt93/monaco-react#15]
Hi, thanks for making this package! The lack of webpack configuration is very nice. 😄 

I'm trying to use MonacoEditor in `readOnly: true` mode as an output visualizer for some text transforms. When the `value` provided to the editor is updated, the editor's contents don't change. It's quite unfortunate.

The issue can be kind of worked around by providing `key={value}`, but that causes the editor to refresh all its DOM elements every update. Rather unfortunate.

Edit: here's a reproducible sample: https://github.com/general-language-syntax/GLS-Web-Client/commit/cd7f0c71ff9953ba6c53652b26a7e2589cba9e16#diff-caa2478e3f773087d1ce9d097daf1d16R35.

Edit 2: interestingly, this bug goes away when `readOnly: true` is not provided.

**Comment by SurenAt93** [comment]
Hello, thank you for your feedback, and for issue.

I could [reproduce](https://codesandbox.io/s/monaco-editorreact---playground-pczh7?fontsize=14) the issue. It’s quite strange. I will examine it more deeply. Will keep you up to date here.

**Comment by SurenAt93** [comment]
@JoshuaKGoldberg the issue is solved in version 1.2.1. Could you please check it. Let me know if it covers your case. Thank you! 🙂

**Comment by JoshuaKGoldberg** [comment]
Confirmed, this works great. Thanks so much for the rapid response & turnaround time! 🙌

**Comment by SurenAt93** [comment]
You're welcome 🙂 🎉 🙌
