### ISSUE TITLE
Syntax Highlighting with Gatsby

### ISSUE THREAD

**Issue by tomthornton** [SurenAt93/monaco-react#16]
The react component works perfectly in my Create React App, but it will not work with Gatsby which I am using for HMR. Does Monaco not work with HMR related things?

**Comment by SurenAt93** [comment]
Actually, it should work with HMR. May I ask you to share the reproducible code segment with the issue? Basically, it can be a codesandbox or Github repo.

Thank you!

**Comment by SurenAt93** [comment]
@tomthornton I checked it. It works well with Gatsby as well as HMR. Maybe, your case is not related to Gatsby or HMR, or I couldn't reproduce it. In any case, I need more info.
