### ISSUE TITLE
Cannot read property 'dispose' of undefined.

### ISSUE THREAD

**Issue by dreamer01** [SurenAt93/monaco-react#17]
**Not an issue.**

The above error occur at Editor.js 

`  var removeEditor = function removeEditor(_) {
    return editorRef.current.dispose();
  };
`
I am using Controlled Editor.
Its working fine in few of my screens/view.

**Comment by SurenAt93** [comment]
Seems like the editor component wants to unmount but can't. Could you please share with me a reproducible code (preferable codesandbox) to check it.

Thank you!
