### ISSUE TITLE
How to access addCommand function?

### ISSUE THREAD

**Issue by prvnbist** [SurenAt93/monaco-react#18]
I need to access `editor.addCommand` function but the `editor` parameter in the below code doesn't have the `addCommand` when logged into the console. Is there any alternate way to add commands?

```
function handleEditorDidMount(_, editor) {
    editorRef.current = editor;
  }
```

Here's the playground example for reference - https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-listening-to-key-events

**Comment by SurenAt93** [comment]
Hello @prvnbist. I just checked it, and it exists. I created an example to demonstrate it. [Please check it](https://codesandbox.io/s/monaco-editorreact---playground-pczh7?fontsize=14).

**Comment by prvnbist** [comment]
Yes, I checked your example and changed it slightly to cover my use case and it works now. I'm sure why it returned the error when I tried it locally but anyway thanks for your quick response.

**Comment by JayaKrishnaNamburu** [comment]
With the lates `4.2.1` i have the same issue. `addCommand` is not exposed with mount callbacks. Any other ways in which we can access `addCommand` on editor. Here is the repro https://codesandbox.io/s/monaco-editor-react---playground-forked-2dyp1?file=/src/index.js

**Comment by SpaceComet** [comment]
@JayaKrishnaNamburu It is `onMount` not `onMonunt`  you didn't spell the word correctly

**Comment by JayaKrishnaNamburu** [comment]
> @JayaKrishnaNamburu It is `onMount` not `onMonunt` you didn't spell the word correctly

Ok my bad with the example. But the issue still exisits 😅

**Comment by SpaceComet** [comment]
I forked your code and I fixed [here](https://codesandbox.io/s/monaco-editor-react---playground-forked-qk2sz?file=/src/index.js) it should work

**Comment by JayaKrishnaNamburu** [comment]
Oh thank you @SpaceComet, i think i got mixed up with both the instances.
