### ISSUE TITLE
onChange method to get user changed code

### ISSUE THREAD

**Issue by subhendukundu** [SurenAt93/monaco-react#2]
Is there **onChange** method to get the changed code?
If not how would one get the change code?

**Comment by SurenAt93** [comment]
Thank you for taking the time to open this issue. 👍

You should use editorDidMount. This function will be called right after monaco editor will be mounted and ready to work. (Read more [here](https://github.com/SurenAt93/monaco-react#props)) It will get the value getter as a first argument and the editor instance as a second argument. So, you can check it out [here](https://codesandbox.io/s/monaco-editor-react-1hzz8).

I hope it helps. 🙂

**Comment by subhendukundu** [comment]
This is great. Thanks
Maybe add this to the readme as well. :)

**Comment by SurenAt93** [comment]
Yes, I agree. I’ll add the whole example. Thank you!
