### ISSUE TITLE
monaco instance example 

### ISSUE THREAD

**Issue by Thara-pearlly** [SurenAt93/monaco-react#20]
using monaco init()
can you be able to give a demo, plz

**Comment by SurenAt93** [comment]
sure. Check the [updated version](https://github.com/SurenAt93/monaco-react/blob/master/README.md#monaco-instance). There is also a demo.

**Comment by Thara-pearlly** [comment]
I cannot use ref in the editor component, since i'm not using react hooks
in my project i cant be using hooks only to this. Is there a way to use to
ref

**Comment by SurenAt93** [comment]
If you need to access to editor instance you can use the class components as well. Check it [here](https://codesandbox.io/s/monaco-editorreact---class-component-t640g?fontsize=14)

**Comment by Thara-pearlly** [comment]
is there any way to use this as class component rather than using as
functional components?

**Comment by Thara-pearlly** [comment]
https://codesandbox.io/s/magical-rain-n0sh4?fontsize=14

in this i tried using the class component as like in your given demo, I
couldn't the get the value in the editor since on "editorDidMount", editor
value is undefined

**Comment by Thara-pearlly** [comment]
https://codesandbox.io/s/magical-rain-n0sh4?fontsize=14

plz refer this url

**Comment by SurenAt93** [comment]
@Thara-pearlly let me know if it helps so we can close this issue.

**Comment by Thara-pearlly** [comment]
yes it helped. Thank you
