### ISSUE TITLE
Request : onBlur for Controlled Editor

### ISSUE THREAD

**Issue by dreamer01** [SurenAt93/monaco-react#21]
Can you add and onBlur function for Controlled editor or please direct me in direction where I can do so. Its an important side effect for any controlled component.

**Comment by Artur93gev** [comment]
Hi.
If the question above is for getting access on container event(nearby you'll see the code fragment, which renders the container: **`<div>`** element):
```
<section style={{ ...styles.wrapper, width, height }}>
      {!isEditorReady && <Loading content={loading} />}
      <div
        ref={containerRef}
        style={{ ...styles.fullWidth, ...(!isEditorReady && styles.hide) }}
      />
</section>
```
then we'll add some prop to access it(something like `wrapperProps`). But if you mean the Editor itself, please take a look at [this section ](https://github.com/SurenAt93/monaco-react#monaco-instance) of [README.md](https://github.com/SurenAt93/monaco-react#monaco-react)

**Comment by dreamer01** [comment]
Hi,

So using the editor ref that I will be getting from editorDidMount side-effect, I am planing to use the [Monaco Editor : ICodeEditor ](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icodeeditor.html#ondidblureditortext) function `onDidBlurEditorText`. 
Hope this solves my problem, also if this works would like to have `onBlur` on Controlled Editor in addition with `onChnage` . 

@Artur93gev thanks for reference.

**Comment by dreamer01** [comment]
So I ended up with below implementation.

```
  editorDidMount = (_, editor) => {
    editor.onDidBlurEditorText(event => this.onBlur(event));
  };

  onBlur = event => {
    if (this.props.onBlur) this.props.onBlur(event);
  };
```
