### ISSUE TITLE
Feature Request : Can we have a local support for cdn file where I have downloaded them already.

### ISSUE THREAD

**Issue by dreamer01** [SurenAt93/monaco-react#22]
Hey,

For monaco editor can we have local support for cdn files where if I have added file localy then I can read it from there in config.

Why: The product where I am using moaco-editor is blocking certain internet request for security resons.

Any kind of solution or alternative approach suggestion is appreciated.

Thanks.

**Comment by SurenAt93** [comment]
Hello @dreamer01, we have already added that functionality. For more please read [this](https://github.com/SurenAt93/monaco-react/issues/12) discussion.

**Comment by dreamer01** [comment]
Thanks, will take a look at this.
