### ISSUE TITLE
Proper monaco typing for Typescript

### ISSUE THREAD

**Issue by stekyne** [SurenAt93/monaco-react#26]
Currently the monaco ref returned via monaco.init() is an "any" type. 
https://github.com/SurenAt93/monaco-react/blob/182da7e727caa7bfc07bcb7c84115a17e73f897d/src/index.d.ts#L172

Would it be possible to return the proper typing as is described here?
https://github.com/microsoft/monaco-editor/blob/master/monaco.d.ts

**Comment by SurenAt93** [comment]
Sure. It will be ready in the next version. I’ll keep you up to date here. Thank you!

**Comment by SurenAt93** [comment]
Hi @stekyne. Please see the updated version of [index.d.ts](https://github.com/SurenAt93/monaco-react/blob/master/src/index.d.ts) file. I think it will cover your needs. Won't it? (the updated version is 2.1.1).

**Comment by stekyne** [comment]
Yeah looks good!
