### ISSUE TITLE
Can't replicate "basic example" from Monaco Playground

### ISSUE THREAD

**Issue by will-hart** [SurenAt93/monaco-react#28]
In the basic example on the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-editor-basic-options), it is possible to set options like `lineNumbers` and `scrollBeyondLastLine` like this:

```js
// Through the options literal, the behaviour of the editor can be easily customized.
// Here are a few examples of config options that can be passed to the editor.
// You can also call editor.updateOptions at any time to change the options.

var editor = monaco.editor.create(document.getElementById("container"), {
	value: "// First line\nfunction hello() {\n\talert('Hello world!');\n}\n// Last line",
	language: "javascript",

	lineNumbers: "off",                 // in particular options like these
	roundedSelection: false,
	scrollBeyondLastLine: true,
	readOnly: true,
	theme: "vs-dark",
});
```

As far as I can tell it is not possible to do this with `monaco.config()`, `monaco.init().then(...)` or through `useRef` and `editorDidMount`. How can I go about providing these configuration options to the editor?

**Comment by SurenAt93** [comment]
Hello. In all components provided by this library, there is a prop called `options`. So, you can easily pass the options object with necessary fields right to that prop. For example:

```js
<Editor
  height="90vh"
  theme="dark"
  language="javascript"
  loading="Loading..."
  value="// something interesting"
  options={{ lineNumbers: "off", readOnly: true, scrollBeyondLastLine: true }}
>
``` 

More about supported props you can read [here](https://github.com/SurenAt93/monaco-react#props)

Also, you can play with options in the [playground](https://monaco-react.surenatoyan.com/) of this library.

I hope it helps. Thank you!

**Comment by will-hart** [comment]
Ah great, thanks, I missed that.
