### ISSUE TITLE
Back button and code paste does't work in mobile browser?

### ISSUE THREAD

**Issue by subhendukundu** [SurenAt93/monaco-react#3]
So I opened the app I made using this, the editor doesn't remove code on back space.
Also not able to paste code on mobile browser.
Replicate code can be found in https://github.com/subhendukundu/gif-code-snippet

Device tested: OnePlus 6 and OnePlus 5t

**Comment by SurenAt93** [comment]
Thank you for taking the time to open this issue. 👍

Unfortunately, the Monaco editor is not supported in mobile browsers. Read more about it [here](https://microsoft.github.io/monaco-editor/) (the 3rd sentence from the top). Also, there is an open [issue](https://github.com/microsoft/monaco-editor/issues/1365#issue-420813035) related to that.

**Comment by subhendukundu** [comment]
Ahh makes sense.

**Comment by karlhorky** [comment]
I also searched for this today, because I was using the new TypeScript Playground (cc @orta) on my phone and wanted to paste in some code - which it didn't let me do.
