### ISSUE TITLE
Error: Unexpected usage / You must define a function MonacoEnvironment.getWorkerUrl or MonacoEnvironment.getWorker

### ISSUE THREAD

**Issue by IamFonky** [SurenAt93/monaco-react#31]
Hello!
I don't know if I am doing something wrong but when I use the Editor component I get strange errors that I didn't have with the webpack plugin for monaco editor.

The error happens when I use monaco editor's variables and your Editor at the same time.

Please try this **[simple example](https://codesandbox.io/s/quirky-chandrasekhar-jwunl)** so you can understand better what i mean.

In this example I just use a KeyCode enum from monaco-editor and your component generate errors.

Thank you for your help!

PS : may be related to [this issue](https://github.com/microsoft/monaco-editor-webpack-plugin/issues/32)

**Comment by SurenAt93** [comment]
Hello @IamFonky!

Interesting behavior. I'll continue examining this example, but before that, I'll suggest another way to use `KeyCode` or other stuff without warnings.

As you have access to [monaco instance](https://github.com/SurenAt93/monaco-react#monaco-instance) you can get `KeyCode` from there:

```js
import { monaco } from "@monaco-editor/react";

monaco.init().then(monaco => console.log(monaco.KeyCode));
```

**Comment by IamFonky** [comment]
Thank you for your quick answer!
I was just thinking of that workaround last night, 

Here is (the example)[https://codesandbox.io/s/eager-booth-jm775] of what you proposed.

**Comment by IamFonky** [comment]
The problem i have now is that i don't want to be in a promise to get these enums/classes of monaco editor.

Here is a very simple modification that i've done on your module that resolve all my problems #33

**Comment by SurenAt93** [comment]
Yes. To be honest, I would prefer more elegant usage of that, but whatever, the idea is to avoid using monaco-editor package directly, when there is a wrapper of it, I mean in the ideal case the wrapper should cover all your needs.

**Comment by IamFonky** [comment]
Yeah but your component is very useful by the way, I like simplicity.

I made a hook to init your module quickly and get the native monaco editor from everywhere

``` typescript
import { useState } from 'react';
import { monaco, Monaco } from '@monaco-editor/react';

export function useMonacoEditor() {
  const [monacoEditor, setMonacoEditor] = useState<Monaco>();
  if (!monacoEditor) {
    monaco.init().then(setMonacoEditor);
  }
  return monacoEditor;
}
```

For the example, for the KeyMod use this hook like this 
``` typescript
const monaco = useMonacoEditor();
[...]
return monaco ? (<p>{monaco.KeyMod.CtrlCmd}</p>) : "Waiting for monaco-editor init"; 
```
I just need to verifiy that the variable exists.

I also made some types to avoid using the monaco-editor ones and risking to call undefined classes :

``` typescript
export type MonacoEditor = Monaco;
export type MonacoEditorProperties = EditorProps['options'];
export type MonacoLangaugesServices = MonacoEditor['languages']['typescript']['typescriptDefaults'];
export type MonacoSCodeEditor = Parameters<EditorDidMount>[1];
export type MonacoSDiffEditor = Parameters<DiffEditorDidMount>[2];
export type MonacoCodeEditor = Parameters<
  Parameters<MonacoSCodeEditor['addAction']>[0]['run']
>[0];
export type MonacoEditorToken = Monaco['Token'];
export type MonacoEditorCursorEvent = Parameters<
  Parameters<MonacoCodeEditor['onDidChangeCursorSelection']>[0]
>[0];
```

**Comment by SurenAt93** [comment]
Great, glad to hear that. If everything is okay, let's close this issue.
