### ISSUE TITLE
Awesome project!

### ISSUE THREAD

**Issue by gillchristian** [SurenAt93/monaco-react#34]
Just wanted to say thanks for this project!

I'm using mdx-deck (which uses Gatsby) and I had all sort of issues with the other version of the Monaco Editor for React. Once I switched to your project it worked out of the box like a charm!

_Just close the issue once you read it, only wanted to say thanks!_

**Comment by SurenAt93** [comment]
@gillchristian 
heey man! You know, you made my day. The day you wrote it, I spilled a coffee on my new Macbook Pro 2019 (I bought it a month ago) and, of course, f***ed it up. I was sitting sad, playing with my phone, and suddenly found this issue. I can't explain the kindness/cuteness of your message at that moment for me and in general.

People like you are just great. It's you, who make open-source more awesome.

Thank you!

**Comment by gillchristian** [comment]
Ohh man, sorry to hear that 😞 Hope you manage to recover it somehow without too much hustle 🤞 

And glad that my message helped at least a tiny bit.

And just if you were curious these are [the slides](https://fp-for-the-people-light.gillchristian.now.sh) and [the repo](https://github.com/gillchristian/fp-for-the-people-v2) where I'm using your project 🤓
