### ISSUE TITLE
Language Validation

### ISSUE THREAD

**Issue by matilem** [SurenAt93/monaco-react#39]
Thank you for making this, it has been really helpful!

The monaco editor currently has some language validation built in for HTML, CSS, JSON, and TypeScript.  I need a way to validate JSON and this is already built in under monaco.languages.json.DiagnosticsOptions.  Could this be added?

**Comment by SurenAt93** [comment]
Hello @matilem, thank you for the feedback.

So, as I understand, you just need to access to Monaco instance. For that purpose, please read [this](https://github.com/SurenAt93/monaco-react#monaco-instance) and also this [discussion](https://github.com/SurenAt93/monaco-react/issues/31).

I hope it helps.

**Comment by matilem** [comment]
Awesome, I totally missed that note. Thank you!

**Comment by suren-atoyan** [comment]
Hey @matilem, now, you can also use [`onValidate`](https://github.com/suren-atoyan/monaco-react#onvalidate)

**Comment by Melancholism** [comment]
> Hey @matilem, now, you can also use [`onValidate`](https://github.com/suren-atoyan/monaco-react#onvalidate)

Hello there. Thank you for your great library.
I have a problem with `onValidate`. When I set the `defaultLanguage` to `html`, the validation is not working. Am I missing something here? Do I have to do some extra steps for validation on HTML?

**Comment by suren-atoyan** [comment]
@Melancholism thanks for your feedback 🙌

I've just checked and I can confirm that it doesn't work for HTML 🤔 Seems like `monaco` doesn't support IntelliSense for HTML, it doesn't seem work in [monaco playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0#example-creating-the-editor-hello-world)

**Comment by Melancholism** [comment]
> @Melancholism thanks for your feedback 🙌
> 
> I've just checked and I can confirm that it doesn't work for HTML 🤔 Seems like `monaco` doesn't support IntelliSense for HTML, it doesn't seem work in [monaco playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0#example-creating-the-editor-hello-world)

Thanks for your attention and fast response.

Ok then, do we have to wait for your kind support to fix it or use a workaround?
