### ISSUE TITLE
[Feature] Add Typescript Support

### ISSUE THREAD

**Issue by qin-guan** [SurenAt93/monaco-react#4]
Would be great to include Typescript support for this package, thanks!

**Comment by SurenAt93** [comment]
Thank you for taking the time to open this issue. 👍

It has already been planned; I'll try to do it today and keep you up to date here.

**Comment by SurenAt93** [comment]
The basic support of Typescript is added to version 1.0.4.

**Comment by qin-guan** [comment]
Thanks!
