### ISSUE TITLE
Prevent use of CDN for offline / support offline mode

### ISSUE THREAD

**Issue by houston88** [SurenAt93/monaco-react#40]
I've noticed when running this in an offline scenario, that it fails to load because it cannot load files from a CDN. Is there a way to use this in an offline mode? Thanks!

**Comment by houston88** [comment]
Taking a look at this to see if that does the trick: https://github.com/microsoft/monaco-editor/blob/master/docs/integrate-amd-cross.md

**Comment by houston88** [comment]
Ah... and https://www.npmjs.com/package/@monaco-editor/react#config

**Comment by SurenAt93** [comment]
Hello @houston88,

Yes, you are right, you can use `monaco.config({ urls: { ... } });` to set the URLs which you need; so you can load them for example from your node_modules. For more see this [discussion](https://github.com/SurenAt93/monaco-react/issues/12).

**Comment by houston88** [comment]
Awesome thanks!
