### ISSUE TITLE
Can't resolve '@monaco-editor/react'

### ISSUE THREAD

**Issue by mean2me** [SurenAt93/monaco-react#45]
I'm running a react app with docker-compose and I keep getting this error:
`Can't resolve '@monaco-editor/react'`

Here is my docker-compose:
```services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web/app:/app
      - /app/node_modules
    ports:
      - '8080:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API_HOST=api
      - API_PORT=3000
      - COMPOSE_HTTP_TIMEOUT=200
    command: npm start
```

---

Here is my Dockerfile:
```
FROM node:alpine

RUN apk update
RUN apk upgrade
RUN command apk add bash

WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

#COPY ./app .

# install and cache app dependencies
COPY ./app/package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts -g --silent

# start app
CMD ["npm", "start"]
```

I verified that folder "@monaco-editor" is present in node_modules folder.

Any idea about what's wrong?

**Comment by SurenAt93** [comment]
Hello @mean2me.

It's only about '@monaco-editor/react'? I mean, can other packages be resolved?

**Comment by mean2me** [comment]
Thanks a lot @SurenAt93 , after investigating my problem was solved after rebuilding the docker-compose service.
For some reason, the mounted volume "/app/node_modules" didn't match with my local folder. Forcing a rebuild with --no-cache solved the problem and now it's working very good.

**Comment by SurenAt93** [comment]
@mean2me glad to hear that and thank you for your support!
