### ISSUE TITLE
[Feature] Adding JSX Support

### ISSUE THREAD

**Issue by qin-guan** [SurenAt93/monaco-react#5]
JSX support is not included in monaco-editor but it would be a plus to have it here!

**Comment by SurenAt93** [comment]
hmmm… interesting topic. I am not sure we will support it in this particular library or not, but at least we can write a complete solution to make jsx supported. It can be a helper for this library or a separate library on top of this. Anyway, let’s still it open for now. We will share thoughts about it.

**Comment by SurenAt93** [comment]
Hello @qin-guan.

After using it for some months, we definitely decided to not go out from borders of native monaco editor, I mean, the library should reflect the native one as much as possible as it's just a wrapper, nothing else.

So, I am going to close it, but if there is something to discuss just write it here.

Thank you for your support!

**Comment by softmarshmallow** [comment]
Still I believe this package should provide the recommended way of supporting jsx/tsx syntax.
(Not support, but at least documenting of this topic.)

**Comment by jeffscottward** [comment]
Yes, don't even know how to do it. Don't know where to start
