### ISSUE TITLE
Global window.monaco object.

### ISSUE THREAD

**Issue by JeremyGrieshop** [SurenAt93/monaco-react#7]
It's useful to get a hold of the window.monaco object for language support, for example.  However, the window.monaco doesn't get injected, I presume, until an instance of a MonacoEditor is created.

Would it be useful (or possible?) to break out that injection into a call that my app could load on startup, so that I can begin pre-registering languages, for instance?  

Currently, I wait until an editorDidMount() call before attempting to register language signatures and autocompletes.

Thanks again!

**Comment by JeremyGrieshop** [comment]
To piggyback on this, everytime a component udpate happens, the browser re-fetches monaco scripts again, which isn't really desirable.  I broke out the script/src/require logic into a separate function and loaded it in my App's main component to get around this.  I was thinking the ideal solution would probably be to export a "Provider" component that could use React Context to initialize and pass down the monaco object via state.

**Comment by JeremyGrieshop** [comment]
This is how I decided to implement it:

https://github.com/JeremyGrieshop/react-monaco-editor

**Comment by SurenAt93** [comment]
As you could have noticed there is a utility that sets up monaco. This utility is being used by Editor/DiffEditor. So, we decided to just export it. For more information take a look at [this discussion](https://github.com/SurenAt93/monaco-react/issues/9), please.
